AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: RSS dynamodb access
Resources:
  ReSStCRUD:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: RSS dynamodb access
      MemorySize: 128
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ReSStCRUD
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python3
