AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Import OPML to ReSSt
Resources:
  ReSStOPMLImport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: Import OPML to ReSSt
      MemorySize: 128
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ReSStOPMLImport
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python3
